services:
  nmap:
    container_name: nmap
    build: nmap/
    # /tmp/logs (rotate daily, log to file, standard format)
    volumes: 
      - C:\TMP:/tmp
    # if breaks, turn off
    #dns:
    #  - 150.250.1.1
    depends_on:
      - db
  db:
    container_name: db
    volumes:
      - C:\TMP\db:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  web:
    container_name: web
    build: web/
    ports:
      - "5000:5000"
    depends_on:
      - db