services:
  nmap:
    container_name: nmap
    build: . 
    volumes: 
      - C:\TMP:/tmp
    dns:
      - 150.250.1.1
    ports: 
      - "5000:5000"
  db:
    container_name: db
    volumes:
      - C:\TMP\db:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
