services:
  nmap:
    container_name: nmap
    build: . 
    # /tmp/logs (rotate daily, log to file, standard format)
    volumes: 
      - C:\TMP:/tmp
    # if breaks, turn off
    dns:
      - 150.250.1.1
  db:
    container_name: db
    volumes:
      - C:\TMP\db:/var/lib/mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  web:
    container_name: web
    build: web/
    ports:
      - "5000:5000"